### ISSUE TITLE
我的近期三个月的 web前端 进阶 TODO list

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#79]
### PC
- [ ] arale（重点研究，研读源码）
- [ ] chart.js(图表库)

### 框架
- [x] React（重点学习，React.js组件开发模式，jsx语法,immutable.js,Virtual DOM，组件间数据流处理：Flux、Reflux、Redux）  http://reactjs.cn/react/docs/why-react.html
- [x] Koa
- [ ] [antd](http://ant.design/) （重点使用）
- [ ] angular.js

思考：开发中解耦逻辑处理与UI渲染，更有效合理的封装通用组件。

### 其他

- [ ] PostCSS，CSSNext、PostHTML

**Comment by Eqistyre** [comment]
> 在 2016年1月13日，22:12，yuwei <notifications@github.com> 写道：
> 
> PC
> 
>  arale（重点研究，研读源码）
>  seajs
>  handlebarsjs
> mobile
> 
>  template7js
>  chartjs
>  fastclickjs
> 框架
> 
>  React（重点学习，Reactjs组件开发模式，jsx语法,immutablejs,Virtual DOM等）
>  组件间数据流处理：Flux、Reflux、Redux
>  Koa
>  antd （重点使用）
>  angularjs
> 思考：开发中解耦逻辑处理与UI渲染，更有效合理的封装通用组件。
> 
> 其他
> 
>  PostCSS，CSSNext、PostHTML
> —
> Reply to this email directly or view it on GitHub <https://github.com/CoderUnion/coderunion-github-talk/issues/79>.
> 
膜～

**Comment by SimplyY** [comment]
@Eqistyre  阿里前端给我发的邮件学习资料。。列出来的，我都不会好吧，，，，

**Comment by Eqistyre** [comment]
里面除了React和angular，chart听过其它都没听过。跪

**Comment by SimplyY** [comment]
@Eqistyre  加油加油，这应该是阿里正式员工要求吧。

**Comment by SimplyY** [comment]
我还是写成我的博客吧，，编辑 issue 累。。

**Comment by xen0n** [comment]
膜 听雨&CoderUnion走出来的BAT第一人么这是

**Comment by SimplyY** [comment]
还没去面试呢，，，气体真菊苣

**Comment by reverland** [comment]
膜，都不知道是啥
